# What language should the messages be in. Accepts 'english', or 'other' only.
MessageLanguage: other
# These can be modified to your liking.
message:
  english:
    NotInFaction: You are not member of any faction
    IncorectChatModeSwitch: 'Error: please use /fc to switch chat mode or'
    SpyModeOn: Spy mode is now on
    SpyModeOff: Spy mode is now off
    NewChatMode: 'Your chat mode has been changed to: '
    FchatoMissType: 'Error: Please use /fco factionname message.'
    FchatoNoOneOnline: 'Error: either no faction member is online or incorrect faction
      name'
    PublicMuteChatOn: 'Public chat is now muted for you'
    PublicMuteChatOff: 'Public chat is no longer muted for you'
    AllyMuteChatOn: 'Ally chat is now muted for you'
    AllyMuteChatOff: 'Ally chat is no longer muted for you'

  other:
    NotInFaction: You are not member of any faction
    IncorectChatModeSwitch: 'Error: please use /fc to switch chat mode or'
    SpyModeOn: Spy mode is now on
    SpyModeOff: Spy mode is now off
    NewChatMode: 'Your chat mode has been changed to: '
    FchatoMissType: 'Error: Please use /fco factionname message.'
    FchatoNoOneOnline: 'Error: either no faction member is online or incorrect faction
      name'
    PublicMuteChatOn: 'Public chat is now muted for you'
    PublicMuteChatOff: 'Public chat is no longer muted for you'
