messages:
  prefix: '&2&lEhita > '
  no-permission: '&cYou don''t have enough permissions to do that!'
  no-console: '&cThis command can only be used in-game.'
  disabled: '&cSeda ei saa loomingulises moodis teha!'
  disabled-interact: '&cSa ei saa seda teha, sest see on pärit loomingulisest moodist.'
  reloaded: '&aConfig reloaded!'
  db-load: '&eLoading data from database...'
  db-save: '&eSaving data to database...'
  db-added: '&eAdded %blocks% new blocks to database.'
  db-removed: '&eDeleted %blocks% old blocks from database.'
  db-deleted: '&eDeleted database. Full restart is required for changes to take effect.'
  db-loaded: '&eLoaded %blocks% blocks from database!'
  db-done: '&aDone! Took %mills%ms'
  creative-on: '&aLoominguline mood sees!'
  creative-off: '&aLoominguline mood väljas!'
  wrong-convert: '&cCorrect usage: /rc convert <cc|gmi|sql>'
  wrong-block: '&cCorrect usage: /rc block <add|remove|info|stats>'
  cancel: '&cCancelled!'
  block-add: '&aRight-click a block/entity you want to add to the database. Type "/rc block add" again to cancel.'
  block-added: '&aAdded %material% to the database!'
  block-remove: '&aRight-click a block/entity you want to remove from the database. Type "/rc block remove" again to cancel.'
  block-removed: '&aRemoved %material% from the database!'
  block-info: '&aRight-click a block/entity you want to know more about. Type "/rc block info" again to cancel.'
  block-info-true: '&aBlock/entity %material% is placed in creative mode!'
  block-info-false: '&aBlock/entity %material% is not placed in creative mode.'
  disabled-region: '&cYou can''t do that outside the allowed region.'
  block-stats: '&eTotal creative placed blocks and entities: %total%'
  disabled-creature: '&cYou can''t do that, because a part of the creature was placed in creative mode.'
